In [1]:
from RLSwitch import RLSwitchEnv
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tqdm import tqdm



In [ ]:
len(env.validActions)

In [15]:
n = 3 # nxn
end_t = 10000 # number of time steps to end an episode after
# lambdaMatrix = [0.5, 0.5, 0.5,
#                 0.5, 0.5, 0.5,
#                 0.5, 0.5, 0.5] # 
env = RLSwitchEnv(n,end_t, lambdaMatrix = None)
for _ in tqdm(range(1000)):
#     env.render()
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    if done:
        env.reset()
env.close()

100%|██████████| 1000/1000 [00:00<00:00, 18357.74it/s]


In [16]:
# Step by step example
n = 3 # nxn
end_t = 15 # number of time steps to end an episode after
# lambdaMatrix = [0.5, 0.5, 0.5,
#                 0.5, 0.5, 0.5,
#                 0.5, 0.5, 0.5] # 
env = RLSwitchEnv(n,end_t, lambdaMatrix = None)
action = env.action_space.sample()
print("State \n" + str(env.state))
print("\nAction \n" + str(action))
print("\nActual Action ",env.validActions[action])

observation, reward, done, info = env.step(action)
print("\nState after action \n")
print(observation)
print("Reward:",reward)

State 
[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 0.]]

Action 
2

Actual Action  [[0 1 0]
 [0 0 1]
 [1 0 0]]

State after action 

[[0. 1. 1.]
 [0. 1. 1.]
 [1. 1. 0.]]
Reward: -1.0


In [6]:
env.validActions

[array([[0, 0, 1],
        [0, 1, 0],
        [1, 0, 0]]),
 array([[0, 0, 1],
        [1, 0, 0],
        [0, 1, 0]]),
 array([[0, 1, 0],
        [0, 0, 1],
        [1, 0, 0]]),
 array([[0, 1, 0],
        [1, 0, 0],
        [0, 0, 1]]),
 array([[1, 0, 0],
        [0, 0, 1],
        [0, 1, 0]]),
 array([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])]