In [1]:
from RLSwitch import RLSwitchEnv
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from tqdm import tqdm


# DQN Implementation
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import Adam
from collections import deque


/home/s2c/anaconda3/envs/RLSwitching/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [ ]:
n = 3 # nxn
end_t = 15 # number of time steps to end an episode after
lambdaMatrix = [0.5, 0.5, 0.5,
                0.5, 0.5, 0.5,
                0.5, 0.5, 0.5] # 
env = RLSwitchEnv(n=3,end_t = 15, lambdaMatrix = lambdaMatrix)
for _ in tqdm(range(1000)):
#     env.render()
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    if done:
        env.reset()
env.close()

In [3]:
# Step by step example
n = 3 # nxn
end_t = 15 # number of time steps to end an episode after
lambdaMatrix = [0.5, 0.5, 0.5,
                0.5, 0.5, 0.5,
                0.5, 0.5, 0.5] # 
env = RLSwitchEnv(n=3,end_t = 15, lambdaMatrix = lambdaMatrix)
action = env.action_space.sample()
print("State \n" + str(env.state))
print("\nAction \n" + str(action))
print("\nActual Action ",env.validActions[action])

observation, reward, done, info = env.step(action)
print("\nState after action \n")
print(observation)
print("Reward:",reward)

State 
[[1. 0. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]

Action 
3

State after action 

[[2. 0. 1.]
 [1. 1. 1.]
 [1. 2. 2.]]
Reward: -6.0


In [ ]:
import numpy as np
import itertools as it
n = 3
allwords = list(it.product(*([(0,1)] * (n**2))))

# convert binary words to NumPy arrays
allarrays = map(np.asarray, allwords)

# convert 1D arrays to 2D arrays
allmatrices = [a.reshape(n,n)  for a in allarrays]


In [ ]:
validSet = []
for each_matrix in allmatrices:
    if env.action_space.contains(each_matrix):
        validSet.append(each_matrix)