In [13]:
from RLSwitch import RLSwitchEnv
import numpy as np
import tensorflow as tf
from keras import backend as K
import matplotlib.pyplot as plt
from gym import spaces
import gym
from tqdm import tqdm

In [48]:
n = 3
end_t = 15
lambdaMatrix = [0.5, 0.5, 0.5,
                0.5, 0.5, 0.5,
                0.5, 0.5, 0.5]
env = RLSwitchEnv(n=3,end_t = 15, lambdaMatrix = lambdaMatrix)
for _ in tqdm(range(1000)):
#     env.render()
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    if done:
        env.reset()
env.close()

100%|██████████| 1000/1000 [00:00<00:00, 9649.42it/s]


In [58]:
# Step by step example
env = RLSwitchEnv(n=3,end_t = 15, lambdaMatrix = lambdaMatrix)
action = env.action_space.sample()
print("State \n" + str(env.state))
print("\nAction \n" + str(action))
observation, reward, done, info = env.step(action)
print("\nState after action \n")
print(observation)
print("Reward:",reward)

State 
[[0. 0. 1.]
 [1. 0. 1.]
 [0. 0. 1.]]

Action 
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]

State after action 

[[0. 1. 1.]
 [0. 0. 2.]
 [1. 1. 2.]]
Reward: -3.0
